### ISSUE TITLE
failed build with linux, ubuntu python3.12

### ISSUE THREAD

**Issue by MetrisVailore** [yungwine/TonTools#27]
failed build with linux, ubuntu python3.12

**Comment by MetrisVailore** [comment]
Failed to build crc16 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (crc16)

**Comment by ArtiikSK** [comment]
you may need to install the Python development package its work for me:

`sudo apt install python3-dev`

**Comment by MetrisVailore** [comment]
same, not working

**Comment by MetrisVailore** [comment]
rewrite it to `sudo apt install python3.12-dev` and it worked

**Comment by MetrisVailore** [comment]
sudo apt install python3.12-dev
